// <auto-generated />
using System;
using LonelyInterview.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LonelyInterview.Infrastructure.Migrations
{
    [DbContext(typeof(LonelyInterviewContext))]
    [Migration("20251115183634_initial3")]
    partial class initial3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("LonelyInterview")
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LonelyInterview.Domain.Entities.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Candidates", "LonelyInterview");
                });

            modelBuilder.Entity("LonelyInterview.Domain.Entities.CandidateInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Biography")
                        .HasColumnType("text");

                    b.Property<string>("WorkExperience")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CandidatesInfo", "LonelyInterview");
                });

            modelBuilder.Entity("LonelyInterview.Domain.Entities.HrManager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("HrManagers", "LonelyInterview");
                });

            modelBuilder.Entity("LonelyInterview.Domain.Entities.Resume", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ActualSkills")
                        .HasColumnType("text");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GitHubUrl")
                        .HasColumnType("text");

                    b.Property<string>("PassiveSkills")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.ToTable("Resumes", "LonelyInterview");
                });

            modelBuilder.Entity("LonelyInterview.Domain.Entities.Vacancy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmploymentType")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MinYearsOfExperience")
                        .HasColumnType("integer");

                    b.Property<string>("NiceToHaveSkills")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequiredSkills")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ResponsibleHrId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("SalaryFrom")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SalaryTo")
                        .HasColumnType("numeric");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WorkFormat")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ResponsibleHrId");

                    b.ToTable("Vacancies", "LonelyInterview");
                });

            modelBuilder.Entity("LonelyInterview.Domain.Entities.Candidate", b =>
                {
                    b.HasOne("LonelyInterview.Domain.Entities.CandidateInfo", "Info")
                        .WithOne("Candidate")
                        .HasForeignKey("LonelyInterview.Domain.Entities.Candidate", "Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Info");
                });

            modelBuilder.Entity("LonelyInterview.Domain.Entities.Resume", b =>
                {
                    b.HasOne("LonelyInterview.Domain.Entities.Candidate", "Candidate")
                        .WithMany("Resumes")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LonelyInterview.Domain.Entities.Vacancy", "Vacancy")
                        .WithOne()
                        .HasForeignKey("LonelyInterview.Domain.Entities.Resume", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("LonelyInterview.Domain.Entities.Vacancy", b =>
                {
                    b.HasOne("LonelyInterview.Domain.Entities.HrManager", "ResponsibleHr")
                        .WithMany("Vacancies")
                        .HasForeignKey("ResponsibleHrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResponsibleHr");
                });

            modelBuilder.Entity("LonelyInterview.Domain.Entities.Candidate", b =>
                {
                    b.Navigation("Resumes");
                });

            modelBuilder.Entity("LonelyInterview.Domain.Entities.CandidateInfo", b =>
                {
                    b.Navigation("Candidate")
                        .IsRequired();
                });

            modelBuilder.Entity("LonelyInterview.Domain.Entities.HrManager", b =>
                {
                    b.Navigation("Vacancies");
                });
#pragma warning restore 612, 618
        }
    }
}
